### ISSUE TITLE
Works only on little-endian systems

### ISSUE THREAD

**Issue by Maccaday** [simpl/ngx_mongo#7]
@renatop7 posted this in another issue:

Hi, I have an interest too in this module.

I tried to add it to nginx but I get the error:
"ngx_mongo works only on little endian platforms"

Is this because of nginx version?

**Comment by Maccaday** [comment]
This issue is almost certainly caused because the system you're trying to install on is 'big endian'.  For reference:

https://en.wikipedia.org/wiki/Endianness

The order of the sequence of bit storage is important, because it affects the way data is read.

There is no reason why this module would not work on a big-endian system, but it would require mapping the bits, and it is unlikely that it would be something that we'd do (for a number of reasons).

You might want to check out an Nginx/Lua-based module to connect to MongoDB:

https://github.com/bigplum/lua-resty-mongol

However, I can neither confirm/deny that it is robust, nor that it works with big endian systems.

On a different note, if you think your site might end up getting heavy load, if you haven't done so already, you might want to check out Couchbase instead of Mongo - scalability is top-notch, and there have been a lot of advancements in the last year or so.  Looking to the future, I feel it's a better choice than Mongo, unless you've already made the choice, obviously.

**Comment by renatop7** [comment]
@Maccaday First of all, thanks for your time to reply.

Yeah, I can't change MongoDB right now. That is why I've been looking for a solution for upstreaming mongo. I even tried the [Nginx stream_core_module](http://nginx.org/en/docs/stream/ngx_stream_core_module.html) but the only way that we managed to make it work was using its HTTP interface, which in our case isn't the best solution, so we are trying to avoid that.
